# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust-bin-simiple-template"
authors = [ "Wink Saville <wink@saville.com>" ]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.76" # Minimum rust version

[dependencies]
